country_names = [
"Debriylor",
"Iechiuton",
"Hoflyae",
"Yoswya",
"Draze",
"Theadal",
"Ascyae",
"Othait",
"Stuik Shia",
"Chian Thyae",
"Zutraogua",
"Ebruedor",
"Fuplurg",
"Pasha",
"Atror"
]

city_names = ["Gluport",
"Okluefgate",
"Word",
"Vrido",
"Icodon",
"Jedale",
"Claridge",
"Yrorsa",
"Chamsas",
"Ylita",
"Qrakson",
"Vravale",
"Kaby",
"Wraso"]

town_names = ["Orla",
              "Chendor",
              "Gragslag",
              "Micer",
              "Cheen",
              "Bleron",
              "Paulsi",
              "Zrekbridge",
              "Wruby",
              "Zucester",
              "Slarhull",
              "Greyrora",
              "Tale",
              "Crester",
              "Vline",
              "Ockbury",
              "Urghbury"]

village_names = ["Luther's Rest",
                 "Erast",
                 "Ballachulish",
                 "Ayrith",
                 "Addersfield",
                 "Auchendinny",
                 "Barmwich",
                 "Rotherham",
                 "Baerney",
                 "Swindlincote",
                 "Panshaw",
                 "Ivrens",
                 "Kilead",
                 "Hwen",
                 "Deathfall",
                 "Haerndean",
                 "Queenstown"]


